<!DOCTYPE html>
<html>
  <body>

    <h2>Error Handling with Arrow Function</h2>
    <p>Catch block displays the error if any.</p>
    <p id="final_result"></p>

    <script>
      const multiply = (m, n) => m * n;
      try {
        document.getElementById("final_result").innerHTML = x;
      } catch(e) {
        document.getElementById("final_result").innerHTML = e.message;
      }
    </script>

  </body>
</html>
